		jeDate("#workfirsttime",{
			isinitVal:false, 
		    format:"hh:mm"
		});//上班允许最早打卡时间
		jeDate("#starttime",{
			isinitVal:false, 
		    format:"hh:mm"
		});//正常上班时间
		jeDate("#worklasttime",{
			isinitVal:false, 
		    format:"hh:mm"
		});//上班允许最晚打卡时间
		jeDate("#leavefirsttime",{
			isinitVal:false, 
		    format:"hh:mm"
		});//下班允许最早打卡时间
		jeDate("#endtime",{
			isinitVal:false, 
		    format:"hh:mm"
		});//具体下班时间
		jeDate("#leavelasttime",{
			isinitVal:false, 
		    format:"hh:mm"
		});//下班允许最晚打卡时间