		    jeDate("#workfirsttime",{
				isinitVal:false, 
			    format:"hh:mm"
			});//上班允许最早打卡时间
			jeDate("#starttime",{
				isinitVal:false, 
			    format:"hh:mm"
			});//正常上班时间
			jeDate("#worklasttime",{
				isinitVal:false, 
			    format:"hh:mm"
			});//上班允许最晚打卡时间
			jeDate("#leavefirsttime",{
				isinitVal:false, 
			    format:"hh:mm"
			});//下班允许最早打卡时间
			jeDate("#endtime",{
				isinitVal:false, 
			    format:"hh:mm"
			});//具体下班时间
			jeDate("#leavelasttime",{
				isinitVal:false, 
			    format:"hh:mm"
			});//下班允许最晚打卡时间
			
		 jeDate("#workfirsttime2",{
				isinitVal:false, 
			    format:"hh:mm"
			});//上班允许最早打卡时间
			jeDate("#starttime2",{
				isinitVal:false, 
			    format:"hh:mm"
			});//正常上班时间
			jeDate("#worklasttime2",{
				isinitVal:false, 
			    format:"hh:mm"
			});//上班允许最晚打卡时间
			jeDate("#leavefirsttime2",{
				isinitVal:false, 
			    format:"hh:mm"
			});//下班允许最早打卡时间
			jeDate("#endtime2",{
				isinitVal:false, 
			    format:"hh:mm"
			});//具体下班时间
			jeDate("#leavelasttime2",{
				isinitVal:false, 
			    format:"hh:mm"
			});//下班允许最晚打卡时间
				
				 jeDate("#workfirsttime3",{
						isinitVal:false, 
					    format:"hh:mm"
					});//上班允许最早打卡时间
					jeDate("#starttime3",{
						isinitVal:false, 
					    format:"hh:mm"
					});//正常上班时间
					jeDate("#worklasttime3",{
						isinitVal:false, 
					    format:"hh:mm"
					});//上班允许最晚打卡时间
					jeDate("#leavefirsttime3",{
						isinitVal:false, 
					    format:"hh:mm"
					});//下班允许最早打卡时间
					jeDate("#endtime3",{
						isinitVal:false, 
					    format:"hh:mm"
					});//具体下班时间
					jeDate("#leavelasttime3",{
						isinitVal:false, 
					    format:"hh:mm"
					});//下班允许最晚打卡时间